name: Prowler Security Audit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prowler-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/aws-cli-action@v2
        with:
          aws-access-key-id: ${{ secrets.PROWLER_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROWLER_USER_SECRET_KEY_ID }}
          aws-region: us-west-1  # Change to your preferred region

      - name: Install Prowler
        run: |
          curl -LO https://github.com/prowler-cloud/prowler/releases/download/v2.6.0/prowler_2.6.0_linux_amd64.zip
          unzip prowler_2.6.0_linux_amd64.zip
          chmod +x prowler
          mv prowler /usr/local/bin/

      - name: Run Prowler Security Audit
        run: |
          prowler -M json -O prowler-report.json
          
      - name: Upload Prowler Report
        uses: actions/upload-artifact@v3
        with:
          name: prowler-report
          path: prowler-report.json
