name: Prowler Security Audit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prowler-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl "https://d1uj6qtbmh3dt5.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.PROWLER_USER_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.PROWLER_USER_SECRET_KEY_ID }}
          aws configure set region us-west-2 # Change to your preferred region

      - name: Install Prowler
        run: |
          curl -LO https://github.com/prowler-cloud/prowler/releases/download/v2.6.0/prowler_2.6.0_linux_amd64.zip
          unzip prowler_2.6.0_linux_amd64.zip
          chmod +x prowler
          sudo mv prowler /usr/local/bin/

      - name: Run Prowler Security Audit
        run: |
          prowler -M json -O prowler-report.json

      - name: Upload Prowler Report
        uses: actions/upload-artifact@v3
        with:
          name: prowler-report
          path: prowler-report.json
